sudo: required

services:
  - docker
  
before_install:
    - docker build -t sinch5/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run sinch5/react-test npm test -- --coverage
    
after_success:
    - docker build -t sinch5/multi-client ./client
    - docker build -t sinch5/multi-nginx ./nginx
    - docker build -t sinch5/multi-server ./server
    - docker build -t sinch5/multi-worker ./worker
    #Loginto docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take thos image and push them to gitgub
    - docker push sinch5/multi-client
    - docker push sinch5/multi-nginx
    - docker push sinch5/multi-server
    - docker push sinch5/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker2
    env: MultiDocker2-env
    bucket_name: elasticbeanstalk-us-east-1-608067911170
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY