sudo: required

services:
  - docker
  
before_install:
    - docker build -t sinch5/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run sinch5/react-test npm test -- --coverage
    
after_success:
    - docker build -t sinch5/multi-client ./client
    - docker build -t sinch5/multi-nginx ./nginx
    - docker build -t sinch5/multi-server ./server
    - docker build -t sinch5/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sinch5/multi-client
    - docker push sinch5/multi-nginx
    - docker push sinch5/multi-server
    - docker push sinch5/multi-worker